#!/usr/bin/env python3

import subprocess
from datetime import datetime

report_file = "logs/security_report.txt"

def run_command(command):
    try:
        result = subprocess.check_output(command, shell=True, stderr=subprocess.STDOUT, universal_newlines=True)
    except subprocess.CalledProcessError as e:
        result = e.output
    return result

def main():
    with open(report_file, "w") as f:
        f.write(f"Security Report - {datetime.now()}\n")
        f.write("="*60 + "\n\n")

        f.write("🔐 Firewall Status:\n")
        f.write(run_command("sudo firewall-cmd --state") + "\n\n")

        f.write("🛡️ SSH Configuration:\n")
        f.write(run_command("sudo grep -E 'Port|PermitRootLogin|PasswordAuthentication' /etc/ssh/sshd_config") + "\n\n")

        f.write("👮 Fail2Ban Status:\n")
        f.write(run_command("sudo systemctl status fail2ban | head -n 10") + "\n\n")

        f.write("🌐 Web Server (NGINX) Status:\n")
        f.write(run_command("sudo systemctl status nginx | head -n 10") + "\n\n")

        f.write("="*60 + "\n")
        f.write("Report generated by AutoSecDeploy\n")

    print(f"✅ Security report generated: {report_file}")

if __name__ == "__main__":
    main()
